name: Artifacts
on:
  workflow_call:
  
permissions:
  id-token: write 
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::682033504346:role/GitHubActionsECRPushRole
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 682033504346.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t dex .

      - name: Tag Docker image
        run: |
          docker tag dex:latest 682033504346.dkr.ecr.ap-south-1.amazonaws.com/my-repo:latest

      - name: Push Docker image to ECR
        run: |
          docker push 682033504346.dkr.ecr.ap-south-1.amazonaws.com/my-repo:latest
