name: Artifacts

on:
  workflow_call:
    inputs:
      publish:
        description: Publish artifacts to the artifact store
        default: false
        required: false
        type: boolean
    secrets:
      AWS_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
    outputs:
      container-image-name:
        description: Container image name
        value: ${{ jobs.container-images.outputs.name }}
      container-image-digest:
        description: Container image digest
        value: ${{ jobs.container-images.outputs.digest }}
      container-image-ref:
        description: Container image ref
        value: ${{ jobs.container-images.outputs.ref }}

permissions:
  contents: read

jobs:
  container-images:
    name: Container Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - alpine
          - distroless
        platform:
          - linux/amd64
          - linux/arm64

    permissions:
      attestations: write
      contents: read
      packages: write
      id-token: write
      security-events: write

    outputs:
      name: ${{ steps.image-name.outputs.value }}
      digest: ${{ steps.build.outputs.digest }}
      ref: ${{ steps.image-ref.outputs.value }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS Public ECR
        id: login-ecr
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Set Image Name
        id: image-name
        run: echo "value=public.ecr.aws/u6x9w5c9/my-repo" >> "$GITHUB_OUTPUT"

      - name: Format Platform Name
        id: platform-name
        run: echo "PLATFORM_TAG=${{ matrix.platform }}" | sed 's/\//-/g' >> $GITHUB_ENV

      - name: Extract Short SHA for Unique Tagging
        id: short-sha
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      ##  Gather Build Metadata
      - name: Gather Build Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.image-name.outputs.value }}
          flavor: latest=false
          tags: |
            type=ref,event=branch
            type=sha,prefix=sha-
            type=semver,pattern={{raw}}
          labels: |
            org.opencontainers.image.title=My Container
            org.opencontainers.image.description=This is a container image built by GitHub Actions.
            org.opencontainers.image.documentation=https://your-docs-url.com/
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Determine build output
        uses: haya14busa/action-cond@v1
        id: build-output
        with:
          cond: ${{ github.event_name == 'push' }}
          if_true: type=image,push=true
          if_false: type=oci,dest=image.tar

      - name: Build Image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ matrix.variant }}
          outputs: ${{ steps.build-output.outputs.value }}
          provenance: false  # Prevents unnecessary provenance attestations

      - name: Set Image Reference
        id: image-ref
        run: echo "value=${{ steps.image-name.outputs.value }}@${{ steps.build.outputs.digest }}" >> "$GITHUB_OUTPUT"

      ##  Install Cosign
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.8.1

      ##  Sign the Image (Without Uploading `.sig` to ECR)
      - name: Sign the images with GitHub OIDC Token
        run: |
          cosign sign --yes --upload=false --output-file=signature.sig ${{ steps.image-name.outputs.value }}@${{ steps.build.outputs.digest }}
        if: inputs.publish

      ##  Upload Cosign Signature as Artifact
      - name: Upload Cosign Signature as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Cosign-Signature-${{ matrix.variant }}-${{ env.PLATFORM_TAG }}"
          path: signature.sig
        if: inputs.publish

      ##  Generate Build Provenance Attestation
      - name: Generate Build Provenance Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ steps.image-name.outputs.value }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
        if: inputs.publish

      ##  Set up Syft for SBOM Generation
      - name: Set up Syft
        uses: anchore/sbom-action/download-syft@v0.18.0

      ##  Generate SBOM (Software Bill of Materials)
      - name: Generate SBOM
        run: syft -o spdx-json=sbom-spdx.json docker://${{ steps.image-name.outputs.value }}@${{ steps.build.outputs.digest }}
        if: inputs.publish

      ##  Upload SBOM as an Artifact
      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "SBOM-${{ matrix.variant }}-${{ env.PLATFORM_TAG }}"
          path: sbom-spdx.json
          retention-days: 5
        if: inputs.publish
