name: Build Binary

on:
  workflow_dispatch:  # Only manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'  # Specify the Go version required by dex

    - name: Build Binary
      run: |
        make build

    - name: Upload Binary as Artifact
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: dex-binary
        path: ./bin/dex  # Adjust the path to where the binary is built
