name: Build and Push Docker Images to AWS Public ECR

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_image: [alpine, distroless]
        arch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::682033504346:role/GitHubActionsECRPushRole  # Your IAM Role ARN
          aws-region: ap-south-1  # Your AWS region

      - name: Log in to AWS Public ECR
        id: login-ecr
        run: |
          aws ecr-public get-login-password --region ap-south-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            public.ecr.aws/u6x9w5c9/my-repo/dex:${{ matrix.base_image }}-${{ matrix.arch }}-latest
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Log out from AWS Public ECR
        run: |
          docker logout public.ecr.aws
